apiVersion: v1
kind: Service
metadata:
  name: resume-nginx-service
  labels:
    app: resume
spec:
  # ClusterIP makes the Service only reachable from within the cluster.
  type: ClusterIP
  selector:
    app: resume # Must match the 'labels' in Deployment's Pod template
  ports:
    - protocol: TCP
      port: 80 # Port service exposed within the cluster
      targetPort: 80 # Port Nginx container is listening on 
      name: http # Nane for port

